name: Get latest release from template
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 15 * *'
jobs:
  steps:
    uses: actions/checkout@v3
    with:
      fetch-depth: 0
  update:
    uses: ObsidianPublisher/actions/.github/workflows/update.yml@main
    with:
      AUTO_MERGE: false
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}